#!/usr/bin/perl

use strict;
use warnings;

use Landlord::Utils;
use Landlord::User;
use Landlord::Group;
if ($ARGV[0]){
   Landlord::Utils::init_db() if $ARGV[0] eq "init";
}

Landlord::Utils::update_active_status(7);
