#!/usr/bin/perl

use strict;
use warnings;

use Landlord::Utils;
use Landlord::User;
use Landlord::Group;
if ($ARGV[0]){
   Landlord::Utils::init_db($dbfile) if not -e $dbfile or $ARGV[0] eq "init";
}
elsif (not -e $dbfile) {
   Landlord::Utils::init_db($dbfile);
}
