#!/usr/bin/perl
# lladdgroup username "full name" email [expire date]

use strict;
use warnings;

package landlord::makeuser;

if (not @ARGV) { die "No group name given\n"; }

my ($gname, $desc) = @ARGV;

# Set the default options. We shall expand this later
my $opts = "";

`groupadd $gname`;
my $gid;
open(GROUP, "</etc/group");
for (<GROUP>){
   if (m/^$gname:.*:(\d+)/){
      $gid = $1;
      last;
   }
}
close GROUP;


my $query;
if ($desc) {
   $query = "INSERT INTO groups (id, name, description) ".
      "VALUES ('$gid' , '$gname', '$desc')";
}
else {
   $query = "INSERT INTO groups (id, name) VALUES ('$gid' , '$gname')";
}


my $dbfile = 'database.db';      # your database file

use sqlite_handler;

sqlite_handler::run_transaction($dbfile, $query);
