#!/usr/bin/perl
# lladduser username "full name" email [expire date]

use strict;
use warnings;

#use Landlord::User qw(add_user);
use Landlord::Landlord qw(add_user);

my $ll = Landlord::Landlord->new();
$ll->add_user(@ARGV);
