#!/usr/bin/perl
# lldelete_user username

#use Unix::Passwd::File qw(delete_ete_user);
#use File::Copy::Recursive "rcopy";

#use Landlord::User qw(delete_user);
use Landlord::Landlord;

my $ll = Landlord::Landlord->new();

$ll -> delete_user(@ARGV);
