#!/usr/bin/perl
# llpassreset username

use pass_generator;

my $uname = $ARGV[0];
my $newpass = pass_generator::generate(8);

`echo $uname:$newpass | chpasswd`;
`echo $newpass > $uname`;
`passwd -e $uname`;
